let productStock = [
    {id: 1, name: "Remera 1", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "S", img: 'img/remera1.jpg', cant:1},
    {id: 2, name: "Remera 2", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "S", img: 'img/remera2.jpg', cant:1},
    {id: 3, name: "Remera 3", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "M", img: 'img/remera3.jpg', cant:1},
    {id: 4, name: "Remera 4", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "M", img: 'img/remera4.jpg', cant:1},
    {id: 5, name: "Remera 5", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "L", img: 'img/remera5.jpg', cant:1},
    {id: 6, name: "Remera 6", type: "remera", desc: "Una remera que va con vos", price: 2800, size: "XL", img: 'img/remera6.jpg', cant:1},
    {id: 7, name: "Buzo 1", type: "buzo", desc: "Un buzo que va con vos", price: 3900, size: "M", img: 'img/buzo1.jpg', cant:1},
    {id: 8, name: "Buzo 2", type: "buzo", desc: "Un buzo que va con vos", price: 3900, size: "L", img: 'img/buzo2.jpg', cant:1},
    {id: 9, name: "Buzo 3", type: "buzo", desc: "Un buzo que va con vos", price: 3900, size: "XL", img: 'img/buzo3.jpg', cant:1},
    {id: 10, name: "Buzo 4", type: "buzo", desc: "Un buzo que va con vos", price: 1200, size: "S", img: 'img/remera1.jpg', cant:1},
    {id: 11, name: "Pantalon 1", type: "pantalon", desc: "Un pantalon que va con vos", price: 1200, size: "S", img: 'img/pant1.jpg', cant:1},
    {id: 12, name: "Pantalon 2", type: "pantalon", desc: "Una pantalon que va con vos", price: 800, size: "M", img: '/img/pant2.jpg', cant:1},
    {id: 13, name: "Pantalon 3", type: "pantalon", desc: "Una pantalon que va con vos", price: 800, size: "L", img: '/img/pant3.jpg', cant:1},
    {id: 14, name: "Zapatillas 1", type: "zapatillas", desc: "Unas zapas que van con vos", price: 5400, size: "other", img: '/img/zap1.jpg', cant:1},
    {id: 15, name: "Zapatillas 2", type: "zapatillas", desc: "Unas zapas que van con vos", price: 5400, size: "other", img: '/img/zap2.jpg', cant:1},
    {id: 16, name: "Zapatillas 3", type: "zapatillas", desc: "Unas zapas que van con vos", price: 5400, size: "other", img: '/img/zap3.jpg', cant:1},
    {id: 17, name: "Zapatillas 4", type: "zapatillas", desc: "Unas zapas que van con vos", price: 5400, size: "other", img: '/img/zap4.jpg', cant:1},
    {id: 18, name: "Mochila 1", type: "mochila", desc: "Una mochila que va con vos", price: 5400, size: "other", img: '/img/mochi1.jpg', cant:1},
    {id: 19, name: "Mochila 2", type: "mochila", desc: "Una mochila que va con vos", price: 5400, size: "other", img: '/img/mochi2.jpg', cant:1},
    {id: 20, name: "Gorra 1", type: "gorra", desc: "Una gorra que va con vos", price: 1500, size: "other", img: '/img/gorra1.jpg', cant:1},
]